[project]
name = "tictactoerl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "keras>=3.12.0",
    "matplotlib>=3.10.8",
    "numpy>=2.3.4",
    "tensorflow>=2.20.0",
]
